USE [FlowerShop]

--Repeatable Reads Solution
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
BEGIN TRAN
SELECT * FROM Greenhouses
WAITFOR DELAY '00:00:05'
SELECT * FROM Greenhouses
COMMIT TRAN