ALTER DATABASE FlowerShop SET ALLOW_SNAPSHOT_ISOLATION ON
ALTER DATABASE FlowerShop SET ALLOW_SNAPSHOT_ISOLATION OFF

USE FlowerShop
GO
WAITFOR DELAY '00:00:10'
BEGIN TRAN
UPDATE Flowers SET flowerName = 'AAA' WHERE fid = 1
WAITFOR DELAY '00:00:10'
COMMIT TRAN