USE FlowerShop
GO
ALTER DATABASE FlowerShop SET ALLOW_SNAPSHOT_ISOLATION OFF
SET TRANSACTION ISOLATION LEVEL SNAPSHOT
BEGIN TRAN
SELECT * FROM Flowers WHERE fid=1
WAITFOR DELAY '00:00:10'
SELECT * FROM Flowers WHERE fid=3
UPDATE Flowers SET flowerName = 'BBB' WHERE fid = 1
COMMIT TRAN